### ISSUE TITLE
When i use inside fragment get Error

### ISSUE THREAD

**Issue by imranemi1221** [DevLight-Mobile-Agency/InfiniteCycleViewPager#21]
Get error when i use it a fragment of "android.support.v4.view.ViewPager" .

```
E/ViewPager: Error changing children drawing order
                                                                  java.lang.IllegalAccessException: access to method denied
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                      at android.support.v4.view.ViewPager.setChildrenDrawingOrderEnabledCompat(ViewPager.java:789)
                                                                      at android.support.v4.view.ViewPager.setPageTransformer(ViewPager.java:768)
                                                                      at com.gigamole.infinitecycleviewpager.HorizontalInfiniteCycleViewPager.setPageTransformer(HorizontalInfiniteCycleViewPager.java:109)
                                                                      at com.gigamole.infinitecycleviewpager.InfiniteCycleManager.<init>(InfiniteCycleManager.java:143)
                                                                      at com.gigamole.infinitecycleviewpager.HorizontalInfiniteCycleViewPager.init(HorizontalInfiniteCycleViewPager.java:30)
                                                                      at com.gigamole.infinitecycleviewpager.HorizontalInfiniteCycleViewPager.<init>(HorizontalInfiniteCycleViewPager.java:26)
                                                                      at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:601)
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:703)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:762)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:771)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                                                                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                      at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1638)
                                                                      at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
                                                                      at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
                                                                      at android.support.v4.view.ViewPager.populate(ViewPager.java:1240)
                                                                      at android.support.v4.view.ViewPager.populate(ViewPager.java:1088)
                                                                      at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
                                                                      at android.view.View.measure(View.java:16677)
                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5286)
                                                                      at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:700)
                                                                      at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90)
                                                                      at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1364)
                                                                      at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:765)
                                                                      at android.view.View.measure(View.java:16677)
                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5286)
                                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                      at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                      at android.view.View.measure(View.java:16677)
                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5286)
                                                                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                      at android.view.View.measure(View.java:16677)
                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5286)
                                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                      at android.view.View.measure(View.java:16677)
                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5286)
                                                                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                      at android.view.View.measure(View.java:16677)
                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5286)
                                                                  	at android.widget
```

**Comment by GIGAMOLE** [comment]
Hello. This is a strange error. 
Try to find some fix. This is about android.

**Comment by z851082677** [comment]
hello,Is this bug fixed?

**Comment by vigneshwaran9494** [comment]
i have face same issue when i am using

**Comment by Utaite** [comment]
How can I fix this?

**Comment by Azuina** [comment]
Have you worked out any approach to solve the problem?

**Comment by duking666** [comment]
is there have other idea to solve the  problem with adding library ad a module in my project

**Comment by duking666** [comment]
is there have other idea to solve the problem without adding library ad a module in my project

**Comment by SnehaInGitHub** [comment]
What will the proguard rules to use this library?
