### ISSUE TITLE
HorizontalInfiniteCycleViewPager.setCurrentItem() not working

### ISSUE THREAD

**Issue by winsontan520** [DevLight-Mobile-Agency/InfiniteCycleViewPager#26]
HorizontalInfiniteCycleViewPager.setCurrentItem() not working if called after view created.

**Comment by kevalpatel2106** [comment]
I am also having the same issue. Here is the error log:
```
     java.lang.NullPointerException: Attempt to invoke virtual method 'int com.radio.canal.customviews.InfiniteCyclePagerAdapter.getCount()' on a null object reference
                                                                     at com.radio.canal.customviews.InfiniteCycleManager.setCurrentItem(InfiniteCycleManager.java:342)
                                                                     at com.radio.canal.customviews.HorizontalInfiniteCycleViewPager.setCurrentItem(HorizontalInfiniteCycleViewPager.java:222)
                                                                     at com.radio.canal.customviews.HorizontalInfiniteCycleViewPager.setCurrentItem(HorizontalInfiniteCycleViewPager.java:216)
                                                                     at com.radio.canal.fragments.RadioPlayerFragment$1.response(RadioPlayerFragment.java:148)
                                                                     at com.radio.canal.network.MyLoopJGet$1.onSuccess(MyLoopJGet.java:62)
                                                                     at com.loopj.android.http.JsonHttpResponseHandler$1$1.run(JsonHttpResponseHandler.java:152)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:158)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by patrykcyrzan** [comment]
Yep, I am also.

**Comment by khokharnikunj8** [comment]
Yup. I am also facing same problem.

**Comment by sinandizdarevic** [comment]
It's working. You have to set your data in init (Kotlin) or constructor (Java) of your adapter. After that, you can setCurrentItem.
